### PR TITLE
Updating About page and adding About link to navigation bar

### PR DESCRIPTION
**Pull request by ssciolla**
This PR adds a link to the About page to the navigation bar and expands the text on that page, using copy provided by @mfldavidson. This PR aims to resolve issues #86 and #138.

The headers on the About page are currently using `h2` tags with `class=header`. This option seemed preferable since the `h1` tag with `class=subheader` previously in use was resulting in rather large headers in bold red. I'd be happy to change or modify this; I'm not sure what's in use around the site. Other suggested changes to the text formatting are welcome.

The About page does not appear to require authentication to visit, if navigated to directly. This seems to be in line with the future approach suggested in issue #86, where we might want to redirect unauthenticated users to the page.

### CODE REVIEW

**Comment by mfldavidson** [comment]
Thank you Sam. Very minor change to request, sorry about this I'm only realizing it given your notes and seeing the changes. Could we keep "About Student Explorer" as h1, then the text below it is just body with no H2 in between, then the other headers in the section are h2? Does that make sense?

**Comment by mfldavidson** [comment]
As in, on line 5, just change h2 to h1, that's the only change

**Comment by mfldavidson** [comment]
Below the hr tag I would actually like to add a little more, I'm sorry for the change. Should I put this in the issue or just here? Or I can add it after we merge, that would be fine.

**Comment by ssciolla** [comment]
@mfldavidson, feel free to describe/provide what you want added as a comment here or on issue #86.

**Comment by ssciolla** [comment]
@mfldavidson, I believe I've made the changes you asked for. Let me know if there are other things you'd like to adjust; I'm fine iterating on this until we're happy with it.

Screen Shot 2019-09-10 at 2 10 05 PM

**Comment by mfldavidson** [comment]
Ok I've reviewed the code and all looks good to me, BUT my one question is, why in the screenshot is the background of the headers blue?

**Pull request merged**
