### PR TITLE
Implement process to retrieve updated metadata rather than using local

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
This will fix issue #12 

This could potentially break at any time unless this is implemented. It doesn't look like SE dev currently uses shibboleth test so we have no way to 100% test that this works. We'll have to get dev set up on shibboleth test instance similar to MyLA. So this might not want to be included in the next release but one right afterward after we can test it.

**Comment by jonespm** [comment]
These 3 new variables 
STUDENT_EXPLORER_SAML_REMOTE_METADATA
STUDENT_EXPLORER_SAML_REMOTE_PEM_FILE
STUDENT_EXPLORER_SAML_DEFAULT_IDP

should be configured the same as MyLA

**Comment by zqian** [comment]
> It doesn't look like SE dev currently uses shibboleth test so we have no way to 100% test that this works.

So we are not able to test this against Shib test, and the current test plan is to make sure we can still sign in to SE test and SE prod, both of which use Shib prod?

I wonder whether GitHub PR supports a good way to put in test plan, like we have done previously with JIRA...

**Comment by zqian** [comment]
I notice SE does not have a .env.sample file in the source code. Unlike what [MyLA project](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/.env.sample)

Could we have a .env.sample file added, with all those newly added variables?

**Comment by jonespm** [comment]
It doesn't look like SE test uses any SAML which is where the problem is.

We can turn it on, but we'd probably have to put in a 4help ticket to get authorized. So this would delay the testing a little. 

I'm not sure about the test plan. Maybe we'd have to integrate and use an external platform like http://www.testquality.com/ if we are going to be using this. I think we'd want to see what the BSA preference is, but we could give this a trial.

**Comment by jonespm** [comment]
Yeah, I could create this file. There are about 20 other variables within this settings.py that are undefined. I don't believe anything is needed to be set to running locally. All of our projects could use much better documentation.

**Comment by zqian** [comment]
> There are about 20 other variables within this settings.py that are undefined. 

By "undefined", do you mean unused by the SE code? If so, those variables can be removed from settings.py.

BTW, testquality looks pretty cool!

**Comment by jonespm** [comment]
Sorry, no I don't mean undefined, I meant undocumented.

**Comment by zqian** [comment]
> I believe we should release this version of SE then switch SE dev over to use Shibboleth test and then we can test this out.

Sounds good. Please go ahead and merge.

**Comment by jonespm** [comment]
I don't want this to be deployed to dev until we do a release or at least tag the current version? Maybe we can talk about at the meeting and plan to release tomorrow morning? 

Did you want to just release with the previous tag you made (that is missing the latest commit)

**Pull request merged**
