### PR TITLE
issue #84 show OpenShift build information inside the /about page

### PR DESCRIPTION
**Pull request by zqian**

### CODE REVIEW

**Comment by zqian** [comment]
It is hard to test locally -- only testable once it is running on OpenShift

**Comment by jonespm** [comment]
You can kind of test locally in the docker if you set the environment variables. You should just be able to add them to your .env file. This would *simulate* Openshift having them. I know those are specific ones are set though so if it works that way it'll work on dev!

**Comment by jonespm** [comment]
I think this is fine removing it entirely from the footer. We might want to make the about link more prominent in a future release as not many users will click on it. (As @mfldavidson mentioned on another ticket) I feel like this version was an indicator for the users to let them know something newer was released (if they notice something like this) and also cross reference the release notes. Though most sites don't display the version they're running prominently on the front page either.

**Comment by zqian** [comment]
Just checked in the view.py changes.

**Pull request merged**
