### PR TITLE
Fixes #189 - Change href of about tab in navbar for advisor w/o student

### LINKED ISSUE #189: 'About' tab doesn't show as active in navigation when accessed via link in advisor_without_students template
https://github.com/tl-its-umich-edu/student_explorer/blob/develop/seumich/templates/seumich/advisor_without_students.html

My bad on not noticing this during testing but the 'About' tab in header nav isn't showing the color that we use to indicate it's the active tab when 'About' page accessed via the link we added for advisors without students. Upon first glance through, I suspect that we need to remove the trailing '/' from the link in the advisor_without_students template.

When 'About' accessed via clicking on 'About' in nav bar, by clicking Student Explorer logo in upper left, or navigating directly to it:
image

When 'About' is accessed via clicking on the link in advisor_without_students.html template (see line 29 in template):
image

### PR DESCRIPTION
**Pull request by susannesheng**
This change fixes issue #189.

I wasn't able to add tests because the current testing framework (I believe) does not include selenium (for clicking on links) or jquery (for testing if classes are active). Please let me know if this assumption is incorrect or if you'd like these tests to be added!

### CODE REVIEW

**Comment by jonespm** [comment]
I believe you could add a test to seumich/tests.py. There should be no need for running any javascript to test this link. I'd maybe add a test like this below. The user mollie doesn't have any students. You could then check the rendered_content. This would going above and beyond and is just to keep the tests updated.

This is incomplete but running this before your fix, the output contains
`                <p>Visit our <a href="/about/">About page</a> to learn more about the purpose and history of Student`

You could probably just verify that the link was changed to match the about URL.

```
    def test_advisor_without_students_about(self):
        self.client.login(username='mollie', password='mollie')
        url = reverse("seumich:advisor", kwargs={"advisor": "mollie"})
        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
        #Verify the renderer_content for the new section is correct
        print(response.rendered_content)
```
`docker exec -it student_explorer /bin/bash -c "echo yes | python manage.py test seumich.tests.SeumichTest.test_advisor_without_students_about"`

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/student_explorer/student_explorer/pullRequest?prid=4556828&bid=15324610)

**Comment by susannesheng** [comment]
The Codacy review finds issue with the hard-coded password, but all test passwords seem to be hard-coded.

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/student_explorer/student_explorer/pullRequest?prid=4556828&bid=15324610)

**Comment by mfldavidson** [comment]
> The Codacy review finds issue with the hard-coded password, but all test passwords seem to be hard-coded.

You are correct. It may be best to use the existing test logins instead of the new one you have added.

**Comment by jonespm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- seumich/tests.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/ITS_Teaching_And_Learning/student_explorer/pullRequest?prid=4556828&bid=15324610)

**Comment by mfldavidson** [comment]
For whatever reason, Codacy liked that better!

**Pull request merged**
